#use_frameworks!

platform :ios, '8.0'

target 'WebLogBridge_Example' do
  pod 'WebLogBridge', :path => '../'

  target 'WebLogBridge_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    #pod 'FBSnapshotTestCase'
    #pod 'Expecta+Snapshots'
  end
end
